// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5jhjgQlRrEUufTAB-T-becOD1iOlhVTs',
    appId: '1:283667069256:web:cd3f0d12a418ab78409b7d',
    messagingSenderId: '283667069256',
    projectId: 'pushnotification-55e77',
    authDomain: 'pushnotification-55e77.firebaseapp.com',
    storageBucket: 'pushnotification-55e77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA967e_NgHWODomF861eauZzYr0UwkJt4c',
    appId: '1:283667069256:android:13ef8c0615e4c8f2409b7d',
    messagingSenderId: '283667069256',
    projectId: 'pushnotification-55e77',
    storageBucket: 'pushnotification-55e77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfv3mm-hJr9pjwAcO3jrbEvXO9pR0IWsU',
    appId: '1:283667069256:ios:e7b60dd5303214ab409b7d',
    messagingSenderId: '283667069256',
    projectId: 'pushnotification-55e77',
    storageBucket: 'pushnotification-55e77.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfv3mm-hJr9pjwAcO3jrbEvXO9pR0IWsU',
    appId: '1:283667069256:ios:e7b60dd5303214ab409b7d',
    messagingSenderId: '283667069256',
    projectId: 'pushnotification-55e77',
    storageBucket: 'pushnotification-55e77.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5jhjgQlRrEUufTAB-T-becOD1iOlhVTs',
    appId: '1:283667069256:web:89652a929bd9abcc409b7d',
    messagingSenderId: '283667069256',
    projectId: 'pushnotification-55e77',
    authDomain: 'pushnotification-55e77.firebaseapp.com',
    storageBucket: 'pushnotification-55e77.firebasestorage.app',
  );
}
